### ISSUE TITLE
Block User

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#13]
As a user I want to block a user and no longer see any content related to them

Sub Stories:
- As a user I want to be able to navigate to the desired account I want to block
- As a user I want to be able to select the account I want to block and view their profile page
- As a user I want to be able to select the block button on the desired account profile page
- As a user I want to be unable to see the blocked account's tweets and interactions on my feed

Task Issues:
- Create a "Block" page

Acceptance Criteria:
- All information containing the user blocked will no longer show up anywhere

**Comment by lmurdock12** [comment]
Closing for now...This is on the lower priority of things to accomplish. We can reopen this if needed
