### ISSUE TITLE
View Account Page

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#23]
Separate the views of the Home Profile Page and visiting someone else's account page.

- [x] Separate navbar buttons
    - [x]  Home Page
       - [x] Edit button #25 
       - [x] Home
       - [x] Followers
       - [x] Following
       - [x] Likes
       - [x] Refresh
       - [x] Logout
    - [x]  Visiting Page
       - [x] Home
       - [x] Followers
       - [x] Following
       - [x] Refresh
       - [x] login/logout group
- [x] Change the right column
   - [x] Home Page
      - [x] Search Bar
      - [x] Who to Follow
   - [x] Visiting Page
      - [x] Search Bar
      - [x] Personal Profile
      - [x] Who to Follow
- [x] add create tweet banner on Home Page

**Comment by lmurdock12** [comment]
This looks like a duplicate issue with the 'Create simple profile page' issue. We should be able to go ahead and delete this for now.

If this is referring to creating an account settings page...then I believe we can remove this from the Sprint 2 milestone

**Comment by bhball22** [comment]
All these pages work and have buttons to get to them, Each just needs enhancement which will have pull request on separate issues.
