### ISSUE TITLE
User Bio

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#24]
As a user when I am on my own profile page I would like to be able to edit my user Bio.

Task Issue:

- [x] Update the base User model to add the bio attribute 
- [x] Update the settings page to allow editing of the User bio
- [x] Dynamically display the current user bio on the profile page

Acceptance Criteria:

A User can successfully click the 'settings' tab and update their own user bio.
A user can not update another user's bio.
A user can see there current bio on the profile page

**Comment by lmurdock12** [comment]
Should we just merge this into account settings? Meaning a user edits their bio inside account settings
