### ISSUE TITLE
Liking Other Tweets

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#29]
As a user I would like to be able to like another user's tweet.
As a user I would like to be able to unlike another user's tweet if I have already liked it.

## Task Breakdown

- [x] #17 Liking another Tweet
- [x] #18 Remove a like

## Acceptance Criteria

* A user can select the like button on a given tweet and it will add it to the database
  * The like button will change to "unlike" once selected
 * A user can not like the same tweet twice
 * A user can not like their own tweet
 * A user can select the unlike button and the existing like will be removed
 * The like counts will be displayed for each users profile

**Comment by lmurdock12** [comment]
#18 Still needs to be completed

**Comment by bhball22** [comment]
#18 Completed
