### ISSUE TITLE
Add photo capabilities to tweets

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#67]
Make tweets be able to be only photos, only text, or both.

- [x] Update Tweet Model
   - [x] Images
   - [x] can be NULL

**Comment by bhball22** [comment]
For some photo ideas of how to work it out.
http://www.learningaboutelectronics.com/Articles/How-to-insert-images-into-a-database-table-with-Python-in-Django.php

**Comment by lmurdock12** [comment]
Complete #89 before this.
