### ISSUE TITLE
Clickable tweets

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#72]
As a user I would like to be able to click a user's username on their tweet and be taken to their profile 

## Tasks
- [x] Update the username link
- [x] Add some basic styling

## Acceptance Criteria

A user can select any username on a tweet and be taken to that persons profile

**Comment by lmurdock12** [comment]
Removing "Hashtag link" and "Tag" link for now since those will be some of the "additional features" for the next sprint, and those actual features need to be implemented first before we can do links

**Comment by lmurdock12** [comment]
@bhball22 What do we want "Tweet Link" to do? Do we need this?

**Comment by bhball22** [comment]
Tweet link, could make that Tweet take up a full page, or that might be a little to much to do for now

**Comment by lmurdock12** [comment]
I am fine to make "Tweet Link" not critical for this sprint. If one of the additional features is something like replies then this would be a good feature to implement next sprint.

**Comment by bhball22** [comment]
That merge looks wonderful, That is a great hyperlink
