### ISSUE TITLE
Create Profile Tabs 

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#86]
As a user I would like to be able to visit a profile page and select different tabs to view different data like tweets, followers, following.

As a user IF I am logged in I would like to be able to hit the settings tab, and edit my account settings. 

## Tasks

- [x] #87 Followers tab
- [x] #87  following tab
- [x] tweets tab
  - [x] The tweets tab is the default tab and technically already implemented...it just needs to be implemented as a button as well so when the 'tweets' button is selected it goes back to the user tweets.
- [x] #88 Settings tab

## Acceptance Criteria

* The user can select the Follower, Following, tweets, and settings tab and view the appropriate data.

## Notes:

 Check out #87 Note section for help on the approach to this problem.

**Comment by bhball22** [comment]
Tabs Created, just information to populate the insides are in the works.

**Comment by bhball22** [comment]
The Pull Request will be tied with #88 and #87
