### ISSUE TITLE
Settings Tab

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#88]
As a user I would like to be able to select the "Settings" tab and and be shown a settings form that contains the current account information with the ability to have it updated. 

Tasks

- [x] Create clickable "POST" buttons for the 'Settings' tab.
- [x] Create a form with entries to username, name, and email address
- [x] Populate the form with the existing values in the account
- [x] Create a button that says "Save settings"
- [x] Edit the "POST" request so that the user's updated setting are saved into the database.
- [x] Make settings button should only show if they are currently logged in and on their account page.

Acceptance Criteria

* The user can select the settings tab, and a form with their existing account information is shown.
* The user can successfully save their updated settings into the database.

**Comment by bhball22** [comment]
Can I have some help with the part of actually get the form to update the information. It does not like to update the information, it keeps telling me that the username already exist. @lmurdock12 May you help out.

**Comment by bhball22** [comment]
I am going to have to do an entire rework on this original game plan, Moving to Milestone 4 for longer development
